test/test_build_libcephfs: fix linking error on gcc11
```
[13/545] Linking CXX executable bin/test_build_libcephfs
FAILED: bin/test_build_libcephfs
: && /usr/bin/ccache /opt/rh/gcc-toolset-11/root/usr/bin/c++ -O2 -g -DNDEBUG -rdynamic src/test/CMakeFiles/test_build_libcephfs.dir/buildtest_skeleton.cc.o -o bin/test_build_libcephfs  -Wl,-rpath,/home/rzarzynsk
i/ceph2/build/lib  lib/libcephfs.so.2.0.0  -lpthread  /usr/lib64/libcrypto.so  -ldl  /usr/lib64/librt.so  -lresolv  /usr/lib64/libcrypto.so  -ldl  /usr/lib64/librt.so  -lresolv  -Wl,-rpath-link,/home/rzarzynski/
ceph2/build/lib  -Wl,--as-needed -latomic && :
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libstdc++_nonshared.a(fs_dir.o): undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXAB
I_1.3'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>
(cherry picked from commit f50c32961519663bd71b98c95ce9ab225415df49)